### ISSUE TITLE
Can't load the addon

### ISSUE THREAD

**Issue by cnyaqi** [zhangyuanwei/node-images#111]
系统环境: macOS10.12.5
node版本: 8.1.4
```
throw new Error('Can\'t load the addon. Issue to: ' + bugUrl);
^

Error: Can't load the addon. Issue to: https://github.com/zhangyuanwei/node-images/issues
    at Object.<anonymous> (/Users/Sun/study/studyNode/node_modules/images/binding.js:62:7)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/Sun/study/studyNode/node_modules/images/index.js:32:15)
    at Module._compile (module.js:569:30)

```

**Comment by FrancoisMentec** [comment]
Same error here:

OS: Fedora release 25 (Twenty Five)
node: 7.10.0
npm: 5.0.3

```
/udd/fmentec/github/himawari-8-wallpaper/node_modules/images/binding.js:61
throw new Error('Can\'t load the addon. Issue to: ' + bugUrl);
^

Error: Can't load the addon. Issue to: https://github.com/zhangyuanwei/node-images/issues
    at Object.<anonymous> (/udd/fmentec/github/himawari-8-wallpaper/node_modules/images/binding.js:61:7)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/udd/fmentec/github/himawari-8-wallpaper/node_modules/images/index.js:32:15)
    at Module._compile (module.js:571:32)
```

**Comment by WangZhuo2015** [comment]
same error
macOS Sirra
node v8.1.4
npm  5.0.3
throw new Error('Can\'t load the addon. Issue to: ' + bugUrl);
^

Error: Can't load the addon. Issue to: https://github.com/zhangyuanwei/node-images/issues
    at Object.<anonymous> (/Users/xxx/node_modules/images/binding.js:61:7)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/xxx/node_modules/images/index.js:32:15)
    at Module._compile (module.js:569:30)

**Comment by tranhiepqna** [comment]
Same error:
Windows 10
Node v8.1.4
npm 5.0.3

**Comment by xiangshouding** [comment]
8.x 还不支持，特别是 windows！

**Comment by suwenjiang** [comment]
Same error:
Windows 10
Node v8.1.4
npm 5.0.3

**Comment by schuesslerf** [comment]
Same error:
Ubuntu 16.04
Node 8.0.0
NPM 5.3.0

**Comment by sanshao** [comment]
same error 

/Users/sanshao/workspace/mywork/mf-admin/node_modules/_images@3.0.0@images/binding.js:61
throw new Error('Can\'t load the addon. Issue to: ' + bugUrl);
^

Error: Can't load the addon. Issue to: https://github.com/zhangyuanwei/node-images/issues
    at Object.<anonymous> (/Users/sanshao/workspace/mywork/mf-admin/node_modules/_images@3.0.0@images/binding.js:61:7)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/sanshao/workspace/mywork/mf-admin/node_modules/_images@3.0.0@images/index.js:32:15)
    at Module._compile (module.js:569:30)

**Comment by insidelabs** [comment]
+1

macOS 10.12.5
node 8.2.1

**Comment by xiangshouding** [comment]
mac 可以尝试如此安装

npm install zhangyuanwei/node-images

**Comment by adamchuan** [comment]
same error
Windows 10
node: 8.3.0
npm 5.3.0

Error: Can't load the addon. Issue to: https://github.com/zhangyuanwei/node-imag
es/issues
    at Object.<anonymous> (C:\Users\adamhe\AppData\Roaming\npm\node_modules\fis3
\node_modules\images\binding.js:61:7)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\adamhe\AppData\Roaming\npm\node_modules\fis3
\node_modules\images\index.js:32:15)
    at Module._compile (module.js:573:30)
> [0x7FFB6A0C4650] ANOMALY: meaningless REX prefix used

**Comment by jdkelley** [comment]
I had this error when trying to use node 8.1.2. I dug a little deeper and found that there are only  [bindings](https://github.com/zhangyuanwei/node-images/tree/master/bindings/linux/x64) for the follow versions of node (for x64 Linux):

* 0.12.0
* 0.8.0
* 0.9.11
* 4.0.0
* 5.0.0

Once I was using a version of node that there are bindings for, it worked. ([nvm](https://github.com/creationix/nvm) is great for switching versions of node.)

---

I'm on x64 Ubuntu 16.04

**Comment by oliversteiner** [comment]
same error:

darwin/x64
node: 8.1.3
npm 5.3.0

please update bindings, thanks

**Comment by yunhongyao** [comment]
same error
Windows 7
node:6.9.4
npm 3.10.10
Error: Can't load the addon. Issue to: https://github.com/zhangyuanwei/node-images/issues Error: Cannot find module './bindings/win32/x64/6.0.0/binding.node'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (D:\midea_project\php\trunk\htdocs\static\wp\src\p_icon_tool\node_modules\images\binding.js:52:34)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Object.<anonymous> (D:\midea_project\php\trunk\htdocs\static\wp\src\p_icon_tool\node_modules\images\binding.js:55:23)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (D:\midea_project\php\trunk\htdocs\static\wp\src\p_icon_tool\node_modules\images\index.js:32:15)
    at Module._compile (module.js:570:32)

**Comment by john2088** [comment]
when I change the nodejs 8 to 6  the error appear

**Comment by xiangshouding** [comment]
+ images@3.0.1
