### ISSUE TITLE
imagescould not find a binding for your current environment: OS X 64-bit with Node.js 6.x

### ISSUE THREAD

**Issue by ghost** [zhangyuanwei/node-images#121]
error mesg:
```bash
/Users/xxx/workspace/coding/com.kuazhan.webcat/node_modules/images/scripts/util/binding.js:15
      throw new Error(errors.missingBinary());
      ^

Error: Missing binding /Users/xxx/workspace/coding/com.kuazhan.webcat/node_modules/images/vendor/darwin-x64-48/binding.node
imagescould not find a binding for your current environment: OS X 64-bit with Node.js 6.x

Found bindings for the following environments:
  - OS X 64-bit with Node.js 6.x
  - OS X 64-bit with Node.js 8.x

This usually happens because your environment has changed since running `npm install`.
Run `npm rebuild images --force` to build the binding for your current environment.
    at module.exports (/Users/xxx/workspace/coding/com.kuazhan.webcat/node_modules/images/scripts/util/binding.js:15:13)
    at Object.<anonymous> (/Users/xxx/workspace/coding/com.kuazhan.webcat/node_modules/images/index.js:32:51)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/xxx/workspace/coding/com.kuazhan.webcat/demo.js:1:78)
```

i try run `npm rebuild images --force` there is 404 error

```bash
npm rebuild images --force
npm WARN using --force I sure hope you know what you are doing.

> images@3.0.1 install /Users/xxx/workspace/coding/com.kuazhan.webcat/node_modules/images
> node ./scripts/install.js

Downloading binary from https://github.com/zhangyuanwei/node-images/releases/download/v3.0.1/darwin-x64-48_binding.node
Cannot download "https://github.com/zhangyuanwei/node-images/releases/download/v3.0.1/darwin-x64-48_binding.node":

HTTP error 404 Not Found

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g.

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080
images@3.0.1 /Users/xxx/workspace/coding/com.kuazhan.webcat/node_modules/images
```

**Comment by dante1977** [comment]
我也有一样的问题 node v6.11.2

**Comment by xiangshouding** [comment]
你的也是 48 不存在？

**Comment by dante1977** [comment]
![image](https://user-images.githubusercontent.com/5715397/31041005-41ce3a9c-a5c1-11e7-9e08-80b51a1023ae.png)
这里，没看到有48的呀 @xiangshouding

**Comment by xiangshouding** [comment]
node 版本是哪个 @dante1977 我怀疑 47 的 48 下就能用。看看你的 node 版本？

**Comment by dante1977** [comment]
6.11.2

**Comment by xiangshouding** [comment]
@dante1977 OK 我回京处理一下。

**Comment by cymmint** [comment]
同问

**Comment by picacav** [comment]
同问，然后我用images版本3.0.0的话就没有封面效果

**Comment by isuoge** [comment]
我也安装报错
PS G:\node_study> npm install images

> images@3.0.1 install G:\node_study\node_modules\images
> node ./scripts/install.js

Downloading binary from https://github.com/zhangyuanwei/node-images/releases/download/v3.0.1/win32-x64-48_binding.node
Cannot download "https://github.com/zhangyuanwei/node-images/releases/download/v3.0.1/win32-x64-48_binding.node":

HTTP error 404 Not Found


Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g.

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080
node_study@1.0.0 G:\node_study
`-- images@3.0.1

npm WARN node_study@1.0.0 No description
npm WARN node_study@1.0.0 No repository field.



node版本 v6.10.0

**Comment by billyjacobson** [comment]
Use node 8.9.3 and that works.

**Comment by bboywen** [comment]
@billyjacobson  it's ok! thanks
