### ISSUE TITLE
win 7 32位  Nodejs 7.2.0异常

### ISSUE THREAD

**Issue by Gitforxuyang** [zhangyuanwei/node-images#124]
E:\NodeJs\fileSystem\node_modules\images\binding.js:61
throw new Error('Can\'t load the addon. Issue to: ' + bugUrl);
^

Error: Can't load the addon. Issue to: https://github.com/zhangyuanwei/node-images/issues
    at Object.<anonymous> (E:\NodeJs\fileSystem\node_modules\images\binding.js:61:7)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (E:\NodeJs\fileSystem\node_modules\images\index.js:32:15)
    at Module._compile (module.js:571:32)

经过多次尝试，发现7以下版本Ok， 一旦运行7以上版本就会出现这个异常。

**Comment by cymmint** [comment]
同问

**Comment by xiangshouding** [comment]
重装试试，记得 7 没做支持。
