### ISSUE TITLE
Can't load the addon(binding.js)

### ISSUE THREAD

**Issue by tigercosmos** [zhangyuanwei/node-images#143]
/Users/tigercosmos/Desktop/line-bot/node_modules/images/binding.js:61
throw new Error('Can\'t load the addon. Issue to: ' + bugUrl);
^

Error: Can't load the addon. Issue to: https://github.com/zhangyuanwei/node-images/issues
    at Object.<anonymous> (/Users/tigercosmos/Desktop/line-bot/node_modules/images/binding.js:61:7)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
    at Module.require (module.js:585:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/tigercosmos/Desktop/line-bot/node_modules/images/index.js:32:15)
    at Module._compile (module.js:641:30)

**Comment by realworld666** [comment]
I also get this with version 3.0.0 since updating to node 10.4 on Windows. I can't install 3.0.1 due to this error

Downloading binary from https://github.com/zhangyuanwei/node-images/releases/download/v3.0.1/win32-x64-64_binding.node
Cannot download "https://github.com/zhangyuanwei/node-images/releases/download/v3.0.1/win32-x64-64_binding.node": 

HTTP error 404 Not Found

**Comment by xiangshouding** [comment]
10.x 还没有编译二进制扩展，如果需要，请搜索 issue 有具体编译的过程说明。

**Comment by tigercosmos** [comment]
應該可以改成 npm install 時讓使用者自己編譯

**Comment by xiangshouding** [comment]
@tigercosmos 依赖环境比较复杂，实在不好弄。这块后续再想办法看看。

**Comment by lidebug** [comment]
wtf, speak english

**Comment by tigercosmos** [comment]
There is no build for the new version, so the user might want to build themselves by following another issue that manifests how to build.
