### ISSUE TITLE
不兼容node v9.4.0 

### ISSUE THREAD

**Issue by goldcome** [zhangyuanwei/node-images#145]
```
C:\test\node_modules\images\scripts\util\binding.js:13
      throw new Error(errors.unsupportedEnvironment());
      ^

Error: imagesdoes not yet support your current environment: Windows 64-bit with
Unsupported runtime (59)
For more information on which environments are supported please see:
https://github.com/undefined/releases/tag/v3.0.1
    at module.exports (C:\Web\data.wxaba.com\node_modules\images\scripts\util\bi
nding.js:13:13)
    at Object.<anonymous> (C:\Web\data.wxaba.com\node_modules\images\index.js:32
:51)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
```

64位windows server2008，node的版本是v9.4.0

**Comment by xiangshouding** [comment]
对，是不支持 9.x

**Comment by zhaoshuxiang** [comment]
有计划什么时间支持 v9.x 吗？

**Comment by cobola** [comment]
还有10.0 💯

**Comment by xiangshouding** [comment]
暂时看，可能后续会用 js 的库改学，支持 node ADDON 太闹心了。

**Comment by superddr** [comment]
那支持哪个版本呢？

**Comment by yecao007** [comment]
也不支持Ubuntu 64位环境下的node v10.4.0的！Error: imagesdoes not yet support your current environment: Linux 64-bit with Unsupported runtime

**Comment by BunnyWithYou** [comment]
@yecao007 用8.11.2应该没问题.... 起码我在windows10 64下是没事... node更新有点快... 还是准备多个node版本吧

**Comment by netcore-jroger** [comment]
请问什么时候支持一波 node 10？

**Comment by ZJUGuoShuai** [comment]
原来是不支持10，我说怎么安装错误了。为什么不在README里说一下呢？

**Comment by FdieZeng** [comment]
演奏怎么做才能支持node10？

**Comment by goldcome** [comment]
很久没更新了 建议先用[node-canvas](https://github.com/Automattic/node-canvas)
