### ISSUE TITLE
imagesdoes not yet support your current environment: Linux 64-bit with Unsupported runtime (67)

### ISSUE THREAD

**Issue by Simple2012hcz** [zhangyuanwei/node-images#161]
/root/programe/testShenm/node_modules/_images@3.0.1@images/scripts/util/binding.js:13
      throw new Error(errors.unsupportedEnvironment());
      ^

Error: imagesdoes not yet support your current environment: Linux 64-bit with Unsupported runtime (67)
For more information on which environments are supported please see:
https://github.com/undefined/releases/tag/v3.0.1
    at module.exports (/root/programe/testShenm/node_modules/_images@3.0.1@images/scripts/util/binding.js:13:13)
    at Object.<anonymous> (/root/programe/testShenm/node_modules/_images@3.0.1@images/index.js:32:51)
    at Module._compile (internal/modules/cjs/loader.js:723:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:734:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Module.require (internal/modules/cjs/loader.js:659:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/root/programe/testShenm/routes/index.js:13:14)
    at Module._compile (internal/modules/cjs/loader.js:723:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:734:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Module.require (internal/modules/cjs/loader.js:659:17)

**Comment by xiangshouding** [comment]
v11.4.0

现在还不支持

CheongHu <notifications@github.com> 于2018年12月15日周六 下午9:38写道：
