### ISSUE TITLE
Issue on Windows 7 32 bits 

### ISSUE THREAD

**Issue by AlexT2** [zhangyuanwei/node-images#168]
I am trying to run this:

`const images = require('images')

images('./rarities/l.png').draw(images('./icons/ark.png'), 0, 0).output('./final.png')`

But I get the following error:

`C:\Users\Alex\Desktop\discordbot>node imgtest.js
C:\Users\Alex\Desktop\discordbot\node_modules\images\scripts\util\binding.js:20
      throw new Error(errors.missingBinary());
      ^

Error: Missing binding C:\Users\Alex\Desktop\discordbot\node_modules\images\vend
or\win32-ia32-64\binding.node
images could not find a binding for your current environment: Windows 32-bit wit
h Node.js 10.x

Found bindings for the following environments:
  - Windows 32-bit with Node.js 10.x

This usually happens because your environment has changed since running `npm ins
tall`.
Run `npm rebuild images --force` to build the binding for your current environme
nt.
    at module.exports (C:\Users\Alex\Desktop\discordbot\node_modules\images\scri
pts\util\binding.js:20:13)
    at Object.<anonymous> (C:\Users\Alex\Desktop\discordbot\node_modules\images\
index.js:32:51)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (C:\Users\Alex\Desktop\discordbot\imgtest.js:1:78)`

Then I ran `npm rebuild images --force` and I get the following error:

`C:\Users\Alex\Desktop\discordbot>npm rebuild images --force
npm WARN using --force I sure hope you know what you are doing.

> images@3.0.2 install C:\Users\Alex\Desktop\discordbot\node_modules\images
> node ./scripts/install.js

Downloading binary from https://github.com/zhangyuanwei/node-images/releases/dow
nload/v3.0.2/win32-ia32-64_binding.node
Cannot download "https://github.com/zhangyuanwei/node-images/releases/download/v
3.0.2/win32-ia32-64_binding.node":

HTTP error 404 Not Found

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g.

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080
images@3.0.2 C:\Users\Alex\Desktop\discordbot\node_modules\images`

(English please)

**Comment by AlexT2** [comment]
Thanks very much

**Comment by AlexT2** [comment]
Can you make for armv71 (raspberry pi 3) too please?
