### ISSUE TITLE
node 8.9.4 npm 5.6.0

### ISSUE THREAD

**Issue by Xuyu1997** [zhangyuanwei/node-images#178]
Unable to save binary /workspace/fd_clean/fd_clean/node_modules/images/vendor/linux-x64-57 : { Error: EACCES: permission denied, mkdir '/workspace/fd_clean/fd_clean/node_modules/images/vendor'
    at Object.fs.mkdirSync (fs.js:885:18)
    at sync (/workspace/fd_clean/fd_clean/node_modules/mkdirp/index.js:71:13)
    at Function.sync (/workspace/fd_clean/fd_clean/node_modules/mkdirp/index.js:77:24)
    at checkAndDownloadBinary (/workspace/fd_clean/fd_clean/node_modules/images/scripts/install.js:138:11)
    at Object.<anonymous> (/workspace/fd_clean/fd_clean/node_modules/images/scripts/install.js:181:1)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
  errno: -13,
  code: 'EACCES',
  syscall: 'mkdir',
  path: '/workspace/fd_clean/fd_clean/node_modules/images/vendor' }

**Comment by Xuyu1997** [comment]
sudo npm resolved
