### ISSUE TITLE
升级计划（2019.9.18）

### ISSUE THREAD

**Issue by xiangshouding** [zhangyuanwei/node-images#193]
现在项目有几个痛点
- 对于特定 node 版本，由于 v8 版本的更新会导致构建的插件不兼容，所以每次都是按照 node  v8 的版本来构建插件版本，node 版本发生跨度比较大的变化，就会导致在新版本上不可用
- 现在的版本不支持安装时自动构建，之所以这样的原因是许多前端同学的环境没有编译环境，所以一般前面都会提供好编译包。但很可惜的点是，编译包逐步递增导致不得不安装时下载。不然包大小无法控制。如果你的网络环境不太行的话就会导致无法下载成功而安装失败
- 由于版本迭代，一些功能被迭代没了，这主要是测试用例没有写全

针对以上的几个问题，本次版本进行如下改造

- 全部使用 n_api 进行编写，把兼容问题交给 Node 自己解决，对于早期的 node 版本逐步不予维护
- 提供完成的测试用例，保持后续的迭代质量
- 安装时尝试编译，如果在已经编译好的插件下载失败时。

预计完成时间 10.1 日前

**Comment by Axure** [comment]
测试用例，选好用什么框架了吗？googletest？或者别的？

**Comment by xiangshouding** [comment]
暂时还没有，gtest 确实比较常用。

**Comment by xiangshouding** [comment]
由于最近绩效忙碌，假期进行更新。

**Comment by YSHIDM** [comment]
大神给力，👍。
我在mac上使用，报错了，
```
/Users/lcy/Project/my/fileUtil/node_modules/images/scripts/util/binding.js:18
      throw new Error(errors.unsupportedEnvironment());
      ^

Error: imagesdoes not yet support your current environment: OS X 64-bit with Unsupported runtime (72)
For more information on which environments are supported please see:
https://github.com/undefined/releases/tag/v3.0.2
    at module.exports (/Users/lcy/Project/my/fileUtil/node_modules/images/scripts/util/binding.js:18:13)
    at Object.<anonymous> (/Users/lcy/Project/my/fileUtil/node_modules/images/index.js:32:51)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/lcy/Project/my/fileUtil/index.js:5:16)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
```
不知道是mac系统的原因，还是node12.13.0的原因。

**Comment by xiangshouding** [comment]
@YSHIDM Node 12 还不支持。

**Comment by YSHIDM** [comment]
OK👌

**Comment by 1316346949** [comment]
支持大佬

**Comment by luoyjx** [comment]
@xiangshouding 下载失败的问题，我是在 gitee 上弄了个类似镜像源的东西，这样临时解决吧，希望能有帮助，参考 👇

https://gitee.com/luoyjx/node-images-bindings

**Comment by smallbad** [comment]
大神，想在node 10 支持了吗

**Comment by xiangshouding** [comment]
完成 Mac 的全平台支持 node 8 以上；

**Comment by xiangshouding** [comment]
#209
