### ISSUE TITLE
修复截取图片，重新编译时gyp报错。

### ISSUE THREAD

**Issue by gxdyxh** [zhangyuanwei/node-images#196]
PS D:\desktop\node-images-master> node-gyp configure
gyp info it worked if it ends with ok
gyp info using node-gyp@6.0.1
gyp info using node@10.16.0 | win32 | x64
gyp info find Python using Python version 2.7.17 found at "E:\tool\Python27\python.exe"
gyp info find VS using VS2019 (16.3.29418.71) found at:
gyp info find VS "d:\Microsoft Visual Studio\2019\Community"
gyp info find VS run with --verbose for detailed information
gyp info spawn E:\tool\Python27\python.exe
gyp info spawn args [ 'C:\\Users\\gqz\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-I',
gyp info spawn args   'D:\\desktop\\node-images-master\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\gqz\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\gqz\\AppData\\Local\\node-gyp\\Cache\\10.16.0\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\gqz\\AppData\\Local\\node-gyp\\Cache\\10.16.0',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\gqz\\AppData\\Roaming\\npm\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\\\Users\\\\gqz\\\\AppData\\\\Local\\\\node-gyp\\\\Cache\\\\10.16.0\\\\<(target_arch)\\\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=D:\\desktop\\node-images-master',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'D:\\desktop\\node-images-master\\build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp: gyp\gyp\libpng.gyp not found (cwd: D:\desktop\node-images-master) while loading dependencies of binding.gyp while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Users\gqz\AppData\Roaming\npm\node_modules\node-gyp\lib\configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Windows_NT 10.0.18362
gyp ERR! command "E:\\tool\\nodejs\\node.exe" "C:\\Users\\gqz\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure"
gyp ERR! cwd D:\desktop\node-images-master
gyp ERR! node -v v10.16.0
gyp ERR! node-gyp -v v6.0.1
gyp ERR! not ok

**Comment by gxdyxh** [comment]
抱歉没有注意到有个文件夹，需要单独下载。
