### ISSUE TITLE
window 下运行出错

### ISSUE THREAD

**Issue by zhifuliu** [zhangyuanwei/node-images#203]
windows 10 专业版 X64.  nodejs 10.15.1

(node:25788) UnhandledPromiseRejectionWarning: Error [50000]: c:\users\xiang\dev\node-images\src\image.cc:581 Unknow format
    at WrappedImage.loadFromBuffer (D:\game\singleGame\autoBuild\node_modules\images\index.js:54:22)
    at WrappedImage.loadFromBuffer (D:\game\singleGame\autoBuild\node_modules\images\index.js:147:34)
    at Function.images.loadFromBuffer (D:\game\singleGame\autoBuild\node_modules\images\index.js:219:27)
    at Function.images.loadFromFile (D:\game\singleGame\autoBuild\node_modules\images\index.js:211:19)
    at images (D:\game\singleGame\autoBuild\node_modules\images\index.js:177:24)
    at main (D:\game\singleGame\autoBuild\runBuild.js:24:17)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:745:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)

**Comment by xiangshouding** [comment]
#209
