### ISSUE TITLE
Unknow format error

### ISSUE THREAD

**Issue by alex-di** [zhangyuanwei/node-images#21]
Error: ../src/Image.cc:268 Unknow format
    at WrappedImage.prototype.loadFromBuffer (/Users/aleksej/PhpstormProjects/node-socket-test/node_modules/images/index.js:18:22)
    at WrappedImage.loadFromBuffer (/Users/aleksej/PhpstormProjects/node-socket-test/node_modules/images/index.js:89:34)
    at Function.images.loadFromBuffer (/Users/aleksej/PhpstormProjects/node-socket-test/node_modules/images/index.js:159:27)
    at Function.images.loadFromFile (/Users/aleksej/PhpstormProjects/node-socket-test/node_modules/images/index.js:151:19)
    at images (/Users/aleksej/PhpstormProjects/node-socket-test/node_modules/images/index.js:119:24)
    at repl:1:2
    at REPLServer.self.eval (repl.js:110:21)
    at Interface.<anonymous> (repl.js:239:12)
    at Interface.EventEmitter.emit (events.js:95:17)
    at Interface._onLine (readline.js:202:10)

Throws at 
var images = require('images')
images(PATH_TO_WORKING_JPEG_I_TRIED_MANY_OF_THEM)

Wtf?

**Comment by guohuihot** [comment]
有没有一个images(xxx).on('error', fn)的事件处理，一报错就断了

**Comment by xiangshouding** [comment]
@guohuihot try 一下
