### ISSUE TITLE
处理超过30000像素的图片的时候，报告了一个错误

### ISSUE THREAD

**Issue by Magicpig** [zhangyuanwei/node-images#25]
/home/weihj/node_modules/images/index.js:45
        return this._handle.toBuffer(type, config);
                            ^
Error: ../src/Image.cc:380 Encode fail.
    at WrappedImage.prototype.encode (/home/weihj/node_modules/images/index.js:45:29)
    at WrappedImage.<anonymous> (/home/weihj/node_modules/images/index.js:89:34)
    at WrappedImage.prototype.save (/home/weihj/node_modules/images/index.js:52:37)
    at WrappedImage.save (/home/weihj/node_modules/images/index.js:89:34)
    at DeepZoom.DumpImages (/home/weihj/DeepZoom.js:235:47)
    at /home/weihj/node_modules/async/lib/async.js:249:17
    at replenish (/home/weihj/node_modules/async/lib/async.js:194:21)
    at /home/weihj/node_modules/async/lib/async.js:206:33
    at /home/weihj/node_modules/async/lib/async.js:251:21
    at DeepZoom.DumpImages (/home/weihj/DeepZoom.js:236:9)

**Comment by luoyjx** [comment]
encode as png maybe OK
