### ISSUE TITLE
Not found /var/vendor/linux-x64-binding.node

### ISSUE THREAD

**Issue by caopengau** [zhangyuanwei/node-images#262]
I'm getting this error when deployed on AWS lambda
Any ideas?
{
    "errorType": "Error",
    "errorMessage": "Not found /var/vendor/linux-x64-binding.node , You can rebuild it, to directory /var,  Run `node-gyp rebuild` Command.",
    "stack": [
        "Error: Not found /var/vendor/linux-x64-binding.node , You can rebuild it, to directory /var,  Run `node-gyp rebuild` Command.",
        "    at module2.exports (/var/task/handler.js:39163:15)",
        "    at node_modules/images/index.js (/var/task/handler.js:39198:36)",
        "    at __require (/var/task/handler.js:8:50)",
        "    at Object.<anonymous> (/var/task/handler.js:39407:29)",
        "    at Module._compile (node:internal/modules/cjs/loader:1256:14)",
        "    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)",
        "    at Module.load (node:internal/modules/cjs/loader:1119:32)",
        "    at Module._load (node:internal/modules/cjs/loader:960:12)",
        "    at Module.require (node:internal/modules/cjs/loader:1143:19)",
        "    at require (node:internal/modules/cjs/helpers:119:18)"
    ]
}

**Comment by jbelelieu** [comment]
Getting the same error on Node20:

node: symbol lookup error: /.../node_modules/images/vendor/linux-x64-binding.node: undefined symbol: _ZN2v87Isolate19CheckMemoryPressureEv
