### ISSUE TITLE
怎么获取一个远程图片

### ISSUE THREAD

**Issue by liuzhengming** [zhangyuanwei/node-images#29]
``` javascript
images(http://d.hiphotos.baidu.com/image/pic/item/58ee3d6d55fbb2fb50264c994d4a20a44623dc2f.jpg)
```

这么写会出现异常，如下：

``` javascript
fs.js:427
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^
Error: ENOENT, no such file or directory 'http://d.hiphotos.baidu.com/image/pic/item/58ee3d6d55fbb2fb50264c994d4a20a44623dc2f.jpg'
    at Object.fs.openSync (fs.js:427:18)
    at Object.fs.readFileSync (fs.js:284:15)
```

**Comment by Maopy** [comment]
我用request下载了一个图片，然后new Buffer(imgData, 'binary')，报了unknown format，是个png图片~

**Comment by xiangshouding** [comment]
你程序怎么写的？@Maopy

**Comment by Maopy** [comment]
var request = require('request');
request(picUrl, function (error, data, imgData) {
  var images = require('images');
  console.log(new Buffer(imgData, 'binary'));
  console.log(images(new Buffer(imgData, 'binary')));
}
大体上是这样~ 删掉了一些不相关代码~ @zhangyuanwei  @xiangshouding

**Comment by xiangshouding** [comment]
```js
var http = require('http');
var fs = require('fs');
http.get(
  'http://img.baidu.com/img/iknow/sula201506/zhengshuang10zhounian200.png',
  function (res) {
    var bufList = [];
    res.on('data', function (c) {
      bufList.push(c);
    });
    res.on('end', function () {
      var images = require('images');
      fs.writeFile(__dirname + '/test.png', Buffer.concat(bufList), function (err) {
        if (err) throw err;
      });
      var img = images(Buffer.concat(bufList));
      img.resize(100);
      img.save(__dirname + '/test_resize.png');
    })
  }
);
```

刚才试了下，应该是获取 `response` 数据的时候对 `Buffer` 进行操作转换出了纰漏。如上代码，自己整个过程就没啥问题。你再研究一下 `request` 这个库的相关参数，应该能解决你的问题。

**Comment by Maopy** [comment]
可以了~ 谢谢~ @xiangshouding
