### ISSUE TITLE
第一次使用，报如下错误：Can\'t load the addon

### ISSUE THREAD

**Issue by corecible** [zhangyuanwei/node-images#60]
安装的话就使用了npm install images。
其他安装包
giflib 4.x.x
libpng 1.5.x
jpeg-turbo 1.x.x
自己手动编译安装。。。

/node_modules/images/binding.js:55
                throw new Error('Can\'t load the addon. Issue to: ' + bugUrl +
                      ^
Error: Can't load the addon. Issue to: https://github.com/zhangyuanwei/node-images/issues Error: Cannot find module './bindings/linux/ia32/0.12.0/binding.node'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/yangqw/spider/zhihuspider/node_modules/images/binding.js:52:34)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at Object.<anonymous> (/home/yangqw/spider/zhihuspider/node_modules/images/binding.js:55:23)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/yangqw/spider/zhihuspider/node_modules/images/index.js:4:15)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
error: Forever detected script exited with code: 1

**Comment by corecible** [comment]
更换为 系统自带的 还是提示如上错误。

**Comment by xiangshouding** [comment]
二进制是需要重新 build 才能用的呀，并不能像依赖 python 装个 python 就行了的呀。

**Comment by corecible** [comment]
不太明白你的意思，是需要把
giflib 4.x.x
libpng 1.5.x
jpeg-turbo 1.x.x
重新编译一下？ 还是需要把image重新编译一下？
目前使用的是npm install images安装。

**Comment by xiangshouding** [comment]
当然是把 images 编译一把啊

**Comment by scalaview** [comment]
Error: Can't load the addon. Issue to: https://github.com/zhangyuanwei/node-images/issues Error: Cannot find module './bindings/linux/x64/4.0.0/binding.node'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Function._load (/usr/local/lib/node_modules/pm2/node_modules/pmx/lib/transaction.js:62:21)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/sp/onepunch/node_modules/images/binding.js:52:34)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function._load (/usr/local/lib/node_modules/pm2/node_modules/pmx/lib/transaction.js:62:21)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/sp/onepunch/node_modules/images/index.js:4:15)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Object.<anonymous> (/home/sp/onepunch/node_modules/images/binding.js:55:23)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function._load (/usr/local/lib/node_modules/pm2/node_modules/pmx/lib/transaction.js:62:21)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/sp/onepunch/node_modules/images/index.js:4:15)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function._load (/usr/local/lib/node_modules/pm2/node_modules/pmx/lib/transaction.js:62:21)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)



遇到一个差不多的，求解决

**Comment by scalaview** [comment]
node  v4.4.7

**Comment by HustFrog** [comment]
change the version to 2.1.10 in package.json like "images": "2.1.10"
