### ISSUE TITLE
[Window 7 Nodejs 4.1.1 64 Bit]  Error: Can't load the addon

### ISSUE THREAD

**Issue by hungchai** [zhangyuanwei/node-images#61]
```
"C:\Program Files (x86)\JetBrains\PhpStorm 9.0.2\bin\runnerw.exe" "C:\Program Files\nodejs\node.exe" app.js
c:\ImageManipulationWeb_Nodejs\node_modules\images\binding.js:55
                throw new Error('Can\'t load the addon. Issue to: ' + bugUrl + ' ' + e.stack);
                ^

Error: Can't load the addon. Issue to: https://github.com/zhangyuanwei/node-images/issues Error: %1 is not a valid Win32 application.
c:\ImageManipulationWeb_Nodejs\node_modules\images\bindings\win32\x64\4.0.0\binding.node
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> 
..........
```

When I try to run on 64bit nodejs environment, the exception will be thrown. But It is able to run on 32bit nodejs environment.

**Comment by xiangshouding** [comment]
下载 64 位的 node 试试；

**Comment by hungchai** [comment]
我的就是64 bit , 但跑不動
跑32bit 是可以的

**Comment by iahu** [comment]
同问，我是windows 32位平台。

**Comment by chrisunshine** [comment]
我的mac也有问题

**Comment by xiangshouding** [comment]
@chrisunshine iojs 都 merge 到 node 里面去了，为啥还要使用 iojs？

**Comment by chrisunshine** [comment]
node -v
v2.3.4
这个版本有问题么

**Comment by xuxiaoyuspallow** [comment]
有人解决了这个问题了吗？

**Comment by xiangshouding** [comment]
@xuxiaoyuspallow 用个 6.0 什么的版本（node）
