### ISSUE TITLE
I found when loading 32bit (CMYK) depth image buffer, the library will throw exception

### ISSUE THREAD

**Issue by hungchai** [zhangyuanwei/node-images#63]
```
UncaughtException!
Error: ..\src\Image.cc:317 Unknow format
    at Error (native)
    at WrappedImage.prototype.loadFromBuffer (c:\ImageManipulationWeb_Nodejs_dev\node_modules\images\index.js:26:22)
    at WrappedImage.loadFromBuffer (c:\ImageManipulationWeb_Nodejs_dev\node_modules\images\index.js:114:34)
    at Function.images.loadFromBuffer (c:\ImageManipulationWeb_Nodejs_dev\node_modules\images\index.js:184:27)
    at images (c:\ImageManipulationWeb_Nodejs_dev\node_modules\images\index.js:144:24)
    at combineImageAndFinalResize 
{}
```

**Comment by xiangshouding** [comment]
图片格式是什么？现在只支持 png,jpeg,gif 的解码；

2015-12-17 11:09 GMT+08:00 hungchai <notifications@github.com>:

**Comment by hungchai** [comment]
![80e3f784-2f2f-03c3-c2dd-64bae9884771](https://cloud.githubusercontent.com/assets/10190523/11888252/8146f120-a576-11e5-84c5-36c3e17ebce3.jpg)

This is JPG but in CYMK format.

**Comment by hungchai** [comment]
how 's the progress?

**Comment by kgdev** [comment]
这个库真是烂啊！

**Comment by xiangshouding** [comment]
@kgdev  感谢反馈

**Comment by hungchai** [comment]
沒辦法？

**Comment by dubiao** [comment]
@kgdev 你牛逼的话请写一个更好的，而不是无端批评别人的成果。
