### ISSUE TITLE
Unknow format error

### ISSUE THREAD

**Issue by huanongying** [zhangyuanwei/node-images#66]
个别jpg格式图片在添加水印处理时，出现如下错误，求帮助，谢谢~
Error: ../src/Image.cc:293 Unknow format
    at WrappedImage.prototype.loadFromBuffer (/deploy/images/index.js:26:22)
    at WrappedImage.loadFromBuffer (/deploy/images/index.js:114:34)
    at Function.images.loadFromBuffer (/deploy/images/index.js:185:27)
    at Function.images.loadFromFile (/deploy/images/index.js:177:19)
    at images (/deploy/images/index.js:144:24)
    at Object.<anonymous> (/deploy/images/test/index.js:6:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)

**Comment by kouguopeng** [comment]
how to solve this problem

**Comment by Skyofmine** [comment]
解决了吗，兄弟
