### ISSUE TITLE
Beyond the pixel size limit. 图片尺寸 ： 21250 * 7500px 大小：139MB

### ISSUE THREAD

**Issue by hpze2000** [zhangyuanwei/node-images#98]
Beyond the pixel size limit. 图片尺寸 ： 21250 * 7500px 大小：139MB

请问， 是不支持 这么大的突破的裁剪吗？ 还是需要设置什么参数 ？

```
Error: ..\src\Image.cc:528 Beyond the pixel size limit.
    at Error (native)
    at WrappedImage.prototype.loadFromBuffer (E:\Project\picadmin\node_modules\images\index.js:54:22)
    at WrappedImage.loadFromBuffer (E:\Project\picadmin\node_modules\images\index.js:142:34)
    at Function.images.loadFromBuffer (E:\Project\picadmin\node_modules\images\index.js:212:27)
    at Function.images.loadFromFile (E:\Project\picadmin\node_modules\images\index.js:204:19)
    at images (E:\Project\picadmin\node_modules\images\index.js:172:24)
    at ReadStream.<anonymous> (E:\Project\picadmin\src\home\controller\picture.js:137:9)
    at emitNone (events.js:86:13)
    at ReadStream.emit (events.js:185:7)
    at fs.js:1766:14
    at FSReqWrap.oncomplete (fs.js:117:15)
```

**Comment by cuitianze** [comment]
默认处理图片宽高为：
#define DEFAULT_WIDTH_LIMIT  10240 // default limit 10000x10000
#define DEFAULT_HEIGHT_LIMIT 10240 // default limit 10000x10000

因此请调用这个函数：
images.setLimit(width, height)

Set the limit size of each image
设置库处理图片的大小限制,设置后对所有新的操作生效(如果超限则抛出异常)

**Comment by wangyan9527** [comment]
设置的没起作用

**Comment by yajore** [comment]
我碰到了同样的问题，设置了没用依然抛出这个问题
